apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: tenant-b
data:
  AUTH_DB_HOST: "34.101.215.47"
  TENANT_DB_HOST: "34.101.215.47"
  PRODUCT_DB_HOST: "34.101.215.47"
  ORDER_DB_HOST: "34.101.215.47"
  WISHLIST_DB_HOST: "34.101.215.47"
  AUTH_DB_NAME: "authentication-db"
  TENANT_DB_NAME: "tenant-db"
  PRODUCT_DB_NAME: "product-db"
  ORDER_DB_NAME: "order-db"
  WISHLIST_DB_NAME: "wishlist-db"
  DEFAULT_DB_PORT: "5432"
