apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: tenant-namespace-b
data:
  AUTH_DB_HOST: "34.50.65.118"
  TENANT_DB_HOST: "34.128.74.185"
  PRODUCT_DB_HOST: "34.101.237.248"
  ORDER_DB_HOST: "34.101.120.132"
  WISHLIST_DB_HOST: "34.101.182.151"
  AUTH_DB_NAME: "authentication-db"
  TENANT_DB_NAME: "tenant-db"
  PRODUCT_DB_NAME: "product-db"
  ORDER_DB_NAME: "order-db"
  WISHLIST_DB_NAME: "wishlist-db"
  DEFAULT_DB_PORT: "5432"
