apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice
  namespace: auth-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-microservice
  template:
    metadata:
      labels:
        app: authentication-microservice
    spec:
      containers:
        - name: authentication-microservice
          image: vinsensiusf/skripsi-authentication-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: TENANT_ID
              value: "00000000-0000-0000-0000-000000000000"
            - name: ADMIN_TENANT_ID
              value: "00000000-0000-0000-0000-000000000000"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: ADMIN_JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: DB_HOST
              value: "authentication-db.db.svc.cluster.local" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@authentication-db:5432/authentication" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-microservice
  namespace: auth-admin
spec:
  selector:
    app: authentication-microservice
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30000 
  
