apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-microservice
  namespace: app-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-microservice
  template:
    metadata:
      labels:
        app: tenant-microservice
    spec:
      containers:
        - name: tenant-microservice
          image: vinsensiusf/skripsi-tenant-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: TENANT_ID
              value: "00000000-0000-0000-0000-000000000000"
            - name: ADMIN_TENANT_ID
              value: "00000000-0000-0000-0000-000000000000"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: AUTH_MS_URL
              value: "http://authentication-microservice.app-admin.svc.cluster.local:8000" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_HOST
              value: "tenant-db.db.svc.cluster.local" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@tenant-db:5432/tenant" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-microservice
  namespace:  app-admin
spec:
  selector:
    app: tenant-microservice
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      # nodePort: 30001
