apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-microservice
  namespace: app-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-microservice
  template:
    metadata:
      labels:
        app: tenant-microservice
    spec:
      containers:
        - name: tenant-microservice
          image: vinsensiusf/skripsi-tenant-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: TENANT_ID
              value: "47dd6b24-0b23-46b0-a662-776158d089ba"
            - name: ADMIN_TENANT_ID
              value: "47dd6b24-0b23-46b0-a662-776158d089ba"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: AUTH_MS_URL
              value: "http://authentication-microservice.app-admin.svc.cluster.local:8000"
            - name: DB_HOST
              value: "tenant-db.db-admin.svc.cluster.local" # IN THE DIFFERENT NAMESPACE< SPECIFY THE NAMESPACE
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@tenant-db:5432/tenant"

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-microservice
  namespace:  app-admin
spec:
  selector:
    app: tenant-microservice
  type: NodePort
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30001
