apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice
  namespace: app-x 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-microservice
  template:
    metadata:
      labels:
        app: authentication-microservice
    spec:
      containers:
        - name: authentication-microservice
          image: vinsensiusf/skripsi-authentication-microservice:latest
          imagePullPolicy: Always  # Uses locally built image in Minikube
          ports:
            - containerPort: 8000
          env:
            - name: TENANT_ID
              value: "08fa2bf2-4ec5-4293-9c0f-26159244896b"
            - name: ADMIN_TENANT_ID
              value: "00000000-0000-0000-0000-000000000000"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: ADMIN_JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: DB_HOST
              value: "authentication-db.db.svc.cluster.local" # IN THE DIFFERENT NAMESPACE< SPECIFY THE NAMESPACE
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@authentication-db:5432/authentication" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-microservice
  namespace: app-x 
spec:
  selector:
    app: authentication-microservice
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30002
