apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice
  namespace: tenant-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
      - name: order-microservice
        image: vinsensiusf/skripsi-orders-microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: TENANT_ID
          value: "08fa2bf2-4ec5-4293-9c0f-26159244896b"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: AUTH_MS_URL
          value: "http://authentication-microservice.auth-x.svc.cluster.local:8000" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
        - name: PRODUCT_MS_URL
          value: "http://product-microservice.product-x.svc.cluster.local:8002" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
        - name: DB_HOST
          value: "order-db.db.svc.cluster.local" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@order-db:5432/order" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: order-microservice
  namespace: tenant-x
spec:
  selector:
    app: order-microservice
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      # nodePort: 30005
  type: ClusterIP
