apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice
  namespace: namespace-tenant-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
      - name: order-microservice
        image: order-microservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: TENANT_ID
          value:  "1e4f3b2a-8d7c-4a9b-bcde-1234567890ab"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: DB_HOST
          value: "order-db.db.svc.cluster.local"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@order-db:5432/order"

---
apiVersion: v1
kind: Service
metadata:
  name: order-microservice
  namespace: namespace-tenant-x
spec:
  selector:
    app: order-microservice
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
