apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice
  namespace: app-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
      - name: order-microservice
        image: vinsensiusf/skripsi-orders-microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: TENANT_ID
          value:  "1e4f3b2a-8d7c-4a9b-bcde-1234567890ab"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: AUTH_MS_URL
          value: "http://authentication-microservice.app-x.svc.cluster.local:8000"
        - name: PRODUCT_MS_URL
          value: "http://product-microservice.app-x.svc.cluster.local:8002"
        - name: DB_HOST
          value: "order-db.db-x.svc.cluster.local"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@order-db:5432/order"

---
apiVersion: v1
kind: Service
metadata:
  name: order-microservice
  namespace: app-x
spec:
  selector:
    app: order-microservice
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30005
  type: NodePort
