apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-microservice
  namespace: app-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-microservice
  template:
    metadata:
      labels:
        app: tenant-microservice
    spec:
      containers:
        - name: tenant-microservice
          image: vinsensiusf/skripsi-tenant-microservice:latest
          imagePullPolicy: Always  # Uses locally built image in Minikube
          ports:
            - containerPort: 8003
          env:
            - name: TENANT_ID
              value: "1e4f3b2a-8d7c-4a9b-bcde-1234567890ab"
            - name: ADMIN_TENANT_ID
              value: "1e4f3b2a-8d7c-4a9b-bcde-1234567890ab"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: AUTH_MS_URL
              value: "http://authentication-microservice.app-x.svc.cluster.local:8000" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_HOST
              value: "tenant-db.db-x.svc.cluster.local" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@tenant-db:5432/tenant" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-microservice
  namespace: app-x
spec:
  selector:
    app: tenant-microservice
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30003
  type: NodePort
