apiVersion: v1
kind: PersistentVolume
metadata:
  name: tenant-db-pv-x
  namespace: db-x
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/tenant-db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenant-db-pvc-x
  namespace: db-x
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-db
  namespace: db-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-db
  template:
    metadata:
      labels:
        app: tenant-db
    spec:
      containers:
        - name: tenant-db
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "tenant"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: tenant-db-pvc-x

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-db
  namespace: db-x
spec:
  selector:
    app: tenant-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
