apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31080

---
apiVersion: v1
kind: Service
metadata:
  name: tenant
spec:
  selector:
    app: tenant
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 31081

---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  type: NodePort
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 31082

---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  selector:
    app: product
  type: NodePort
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 31083

---
apiVersion: v1
kind: Service
metadata:
  name: wishlist
spec:
  selector:
    app: wishlist
  type: NodePort
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
      nodePort: 31084
