apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USER: cG9zdGdyZXM= # "postgres" dalam base64
  DB_PASSWORD: cG9zdGdyZXM= # "postgres" dalam base64
  JWT_SECRET: YXV0aF9tc19qd3Rfc2VjcmV0 # "auth_ms_jwt_secret" dalam base64
