---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skripsi-auth-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: skripsi-auth
  template:
    metadata:
      labels:
        app: skripsi-auth
    spec:
      containers:
      - name: skripsi-auth
        image: vincentsuryakimui/skripsi-auth:040524
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: TENANT_ID
          value: "cab079f7-def1-4419-9dcf-afdc78bf5ac3"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: ADMIN_JWT_SECRET
          value: "admin_auth_ms_jwt_secret"
        - name: ADMIN_TENANT_ID
          value: "00000000-0000-0000-0000-000000000000"
        - name: DB_HOST
          value: "35.185.179.142"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skripsi-tenant-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: skripsi-tenant
  template:
    metadata:
      labels:
        app: skripsi-tenant
    spec:
      containers:
      - name: skripsi-tenant
        image: vincentsuryakimui/skripsi-tenant:040524
        ports:
        - containerPort: 8003
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: AUTH_MS_URL
          value: "http://skripsi-auth-service:8000"
        - name: DB_HOST
          value: "34.126.130.185"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skripsi-products-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: skripsi-products
  template:
    metadata:
      labels:
        app: skripsi-products
    spec:
      containers:
      - name: skripsi-products
        image: vincentsuryakimui/skripsi-products:040524
        ports:
        - containerPort: 8002
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: TENANT_ID
          value: "cab079f7-def1-4419-9dcf-afdc78bf5ac3"
        - name: DB_HOST
          value: "34.143.241.22"
        - name: AUTH_MS_URL
          value: "http://34.143.200.223:32232"
        - name: TENANT_MS_URL
          value: "http://34.143.200.223:32233"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skripsi-wishlist-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: skripsi-wishlist
  template:
    metadata:
      labels:
        app: skripsi-wishlist
    spec:
      containers:
      - name: skripsi-wishlist
        image: vincentsuryakimui/skripsi-wishlist:040524
        ports:
        - containerPort: 8004
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: TENANT_ID
          value: "cab079f7-def1-4419-9dcf-afdc78bf5ac3"
        - name: DB_HOST
          value: "34.87.149.238"
        - name: AUTH_MS_URL
          value: "http://skripsi-auth-service:8000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skripsi-orders-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: skripsi-orders
  template:
    metadata:
      labels:
        app: skripsi-orders
    spec:
      containers:
      - name: skripsi-orders
        image: vincentsuryakimui/skripsi-orders:040524
        ports:
        - containerPort: 8001
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: TENANT_ID
          value: "cab079f7-def1-4419-9dcf-afdc78bf5ac3"
        - name: DB_HOST
          value: "34.126.78.2"
        - name: AUTH_MS_URL
          value: "http://skripsi-auth-service:8000"
        - name: PRODUCT_MS_URL
          value: "http://skripsi-products-service:8002"