---
apiVersion: v1
kind: Service
metadata:
  name: skripsi-auth-service
spec:
  type: NodePort
  selector:
    app: skripsi-auth
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: skripsi-tenant-service
spec:
  type: NodePort
  selector:
    app: skripsi-tenant
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: skripsi-products-service
spec:
  type: NodePort
  selector:
    app: skripsi-products
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: skripsi-wishlist-service
spec:
  type: NodePort
  selector:
    app: skripsi-wishlist
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004

---
apiVersion: v1
kind: Service
metadata:
  name: skripsi-orders-service
spec:
  type: NodePort
  selector:
    app: skripsi-orders
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001