---
apiVersion: v1
kind: Service
metadata:
  name: skripsi-auth-service
spec:
  type: NodePort
  selector:
    app: skripsi-auth
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32232

---
apiVersion: v1
kind: Service
metadata:
  name: skripsi-tenant-service
spec:
  type: NodePort
  selector:
    app: skripsi-tenant
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 32233