apiVersion: v1
kind: Namespace
metadata:
  name: root-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-tenant-x
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-tenant-y
---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: db-admin
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: db-x
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: db-y
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth-admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth-x
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-x
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-x
---
apiVersion: v1
kind: Namespace
metadata:
  name: order-x
---
apiVersion: v1
kind: Namespace
metadata:
  name: wishlist-x
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth-y
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-y
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-y
---
apiVersion: v1
kind: Namespace
metadata:
  name: order-y
---
apiVersion: v1
kind: Namespace
metadata:
  name: wishlist-y
---

---
apiVersion: v1
kind: Namespace
metadata:
  name: db
---

---
# Run the command below in terminal to set the parent namespaces
# kubectl hns set namespace-admin --parent=root-namespace
# kubectl hns set namespace-tenant-x --parent=root-namespace
# kubectl hns set namespace-tenant-y --parent=root-namespace
# kubectl hns set auth-admin --parent=namespace-admin
# kubectl hns set tenant-admin --parent=namespace-admin
# kubectl hns set product-admin --parent=namespace-admin
# kubectl hns set order-admin --parent=namespace-admin
# kubectl hns set wishlist-admin --parent=namespace-admin
# kubectl hns set auth-x --parent=namespace-admin
# kubectl hns set tenant-x --parent=namespace-admin
# kubectl hns set product-x --parent=namespace-admin
# kubectl hns set order-x --parent=namespace-admin
# kubectl hns set wishlist-x --parent=namespace-admin
# kubectl hns set auth-y --parent=namespace-admin
# kubectl hns set tenant-y --parent=namespace-admin
# kubectl hns set product-y --parent=namespace-admin
# kubectl hns set order-y --parent=namespace-admin
# kubectl hns set wishlist-y --parent=namespace-admin
# kubectl hns set db --parent=root-namespace


# WILL NOT BE USED
# kubectl hns set db-admin --parent=namespace-admin
# kubectl hns set db-x --parent=namespace-tenant-x
# kubectl hns set db-y --parent=namespace-tenant-y
