apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice
  namespace:  app-y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-microservice
  template:
    metadata:
      labels:
        app: authentication-microservice
    spec:
      containers:
        - name: authentication-microservice
          image: vinsensiusf/skripsi-authentication-microservice:latest
          imagePullPolicy: Always  # Uses locally built image in Minikube
          ports:
            - containerPort: 8000
          env:
            - name: TENANT_ID
              value: "a7c8d9e0-1b2f-4d3c-8e7a-6b5c4d3f2a1e"
            - name: ADMIN_TENANT_ID
              value: "a7c8d9e0-1b2f-4d3c-8e7a-6b5c4d3f2a1e"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: ADMIN_JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: DB_HOST
              value: "authentication-db.db-y.svc.cluster.local" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@authentication-db:5432/authentication" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-microservice
  namespace: app-y
spec:
  selector:
    app: authentication-microservice
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
  type: NodePort
