apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice
  namespace:  namespace-tenant-y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-microservice
  template:
    metadata:
      labels:
        app: authentication-microservice
    spec:
      containers:
        - name: authentication-microservice
          image: authentication-microservice:latest
          imagePullPolicy: Never  # Uses locally built image in Minikube
          ports:
            - containerPort: 8000
          env:
            - name: TENANT_ID
              value:  'a7c8d9e0-1b2f-4d3c-8e7a-6b5c4d3f2a1e'
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: ADMIN_JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: DB_HOST
              value: "authentication-db.db-y.svc.cluster.local" # IN THE DIFFERENT NAMESPACE< SPECIFY THE NAMESPACE
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@authentication-db:5432/authentication"

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-microservice
  namespace: namespace-tenant-y
spec:
  selector:
    app: authentication-microservice
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
  type: NodePort
