apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice
  namespace: namespace-tenant-y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
      - name: order-microservice
        image: order-microservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: TENANT_ID
          value:  "a7c8d9e0-1b2f-4d3c-8e7a-6b5c4d3f2a1e"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: DB_HOST
          value: "order-db.db.svc.cluster.local"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@order-db:5432/order"

---
apiVersion: v1
kind: Service
metadata:
  name: order-microservice
  namespace: namespace-tenant-y
spec:
  selector:
    app: order-microservice
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
