apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice
  namespace: app-y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
      - name: order-microservice
        image: vinsensiusf/skripsi-orders-microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: TENANT_ID
          value: "8554fa4b-4c70-4011-b88a-c40b7f54d73d"
        - name: JWT_SECRET
          value: "auth_ms_jwt_secret"
        - name: AUTH_MS_URL
          value: "http://authentication-microservice.app-y.svc.cluster.local:8000" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
        - name: PRODUCT_MS_URL
          value: "http://product-microservice.app-y.svc.cluster.local:8002" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
        - name: DB_HOST
          value: "order-db.db.svc.cluster.local" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@order-db:5432/order" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: order-microservice
  namespace: app-y
spec:
  selector:
    app: order-microservice
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      # nodePort: 30010
  type: ClusterIP
