apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-microservice
  namespace: app-y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-microservice
  template:
    metadata:
      labels:
        app: product-microservice
    spec:
      containers:
        - name: product-microservice
          image: vinsensiusf/skripsi-products-microservice:latest
          imagePullPolicy: Always  # Uses locally built image in Minikube
          ports:
            - containerPort: 8002
          env:
            - name: product_ID
              value: "8554fa4b-4c70-4011-b88a-c40b7f54d73d"
            - name: TENANT_ID
              value: "8554fa4b-4c70-4011-b88a-c40b7f54d73d"
            - name: ADMIN_TENANT_ID
              value: "00000000-0000-0000-0000-000000000000"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: AUTH_MS_URL
              value: "http://authentication-microservice.app-admin.svc.cluster.local:8000" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: TENANT_MS_URL
              value: "http://tenant-microservice.app-admin.svc.cluster.local:8003" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_HOST
              value: "product-db.db.svc.cluster.local" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@product-db:5432/product" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: product-microservice
  namespace: app-y
spec:
  selector:
    app: product-microservice
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      # nodePort: 30009
  type: ClusterIP
