apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-microservice
  namespace: app-y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-microservice
  template:
    metadata:
      labels:
        app: tenant-microservice
    spec:
      containers:
        - name: tenant-microservice
          image: vinsensiusf/skripsi-tenant-microservice:latest
          imagePullPolicy: Always  # Uses locally built image in Minikube
          ports:
            - containerPort: 8003
          env:
            - name: TENANT_ID
              value: "8554fa4b-4c70-4011-b88a-c40b7f54d73d"
            - name: JWT_SECRET
              value: "auth_ms_jwt_secret"
            - name: AUTH_MS_URL
              value: "http://authentication-microservice.app-y.svc.cluster.local:8000" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_HOST
              value: "tenant-db.db.svc.cluster.local" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@tenant-db:5432/authentication" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: tenant-microservice
  namespace: app-y
spec:
  selector:
    app: tenant-microservice
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      # nodePort: 30008
  type: ClusterIP
