apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-microservice
  namespace: wishlist-y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-microservice
  template:
    metadata:
      labels:
        app: wishlist-microservice
    spec:
      containers:
      - name: wishlist-microservice
        image:  vinsensiusf/skripsi-wishlist-microservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
        env:
          - name: TENANT_ID
            value:  "8554fa4b-4c70-4011-b88a-c40b7f54d73d"
          - name: AUTH_MS_URL
            value: "http://authentication-microservice.auth-y.svc.cluster.local:8000" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
          - name: JWT_SECRET
            value: "auth_ms_jwt_secret"
          - name: DB_HOST
            value: "wishlist-db.db.svc.cluster.local" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: DB_PORT
            value: "5432"
          - name: DATABASE_URL
            value: "postgres://postgres:postgres@wishlist-db:5432/wishlist" #NEED TO BE CHANGE WHEN DEPLOYED TO CLOUD

---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-microservice
  namespace: wishlist-y
spec:
  selector:
    app: wishlist-microservice
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
      # nodePort: 30011
  type: ClusterIP
