apiVersion: v1
kind: Service
metadata:
  name: admin-authentication-nodeport
  namespace: ns-admin
spec:
  selector:
    app: authentication
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: admin-tenant-nodeport
  namespace: ns-admin
spec:
  selector:
    app: tenant
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      nodePort: 30081
  type: NodePort