apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 5
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: dpaalh/authentication:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "150m"
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: TENANT_ID
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: ADMIN_TENANT_ID
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JWT_SECRET
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: ADMIN_JWT_SECRET
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: AUTH_DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: AUTH_DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DEFAULT_DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
        - name: tenant
          image: dpaalh/tenant:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "150m"
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: TENANT_ID
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: ADMIN_TENANT_ID
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: TENANT_DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: TENANT_DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DEFAULT_DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: AUTH_MS_URL
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: AUTHENTICATION_URL
