apiVersion: v1
kind: ResourceQuota
metadata:
  name: hrq-child-quota
  namespace: tenant-namespace-a
spec:
  hard:
    limits.cpu: "1"
    limits.memory: "2Gi" #"16Gi"
    requests.cpu: "1"
    requests.memory: "2Gi" #"8Gi"
    pods: "50"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hrq-child-quota
  namespace: tenant-namespace-b
spec:
  hard:
    limits.cpu: "1"
    limits.memory: "2Gi" #"16Gi"
    requests.cpu: "1"
    requests.memory: "2Gi" #"8Gi"
    pods: "50"
