apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: admin
spec:
  selector:
    app: authentication
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: tenant
  namespace: admin
spec:
  selector:
    app: tenant
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
